language: node_js
node_js:
  - "0.12"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends libvips-dev
env:
  - PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/X11/lib/pkgconfig"